import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      {/* <MainHead {...props} /> */}
      {/* <style>
        html.lenis {
          height: auto;
		}
        .lenis.lenis-smooth {
          scroll - behavior: auto;
		}
        .lenis.lenis-smooth [data-lenis-prevent] {
          overscroll - behavior: contain;
		}
        .lenis.lenis-stopped {
          overflow: hidden;
		}
      </style> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-white selection:text-neutral-900 text-black`}
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
